### ISSUE TITLE
请教：执行七脉main.py报错 TypeError: 'undefined' 为 null 或不是对象

### ISSUE THREAD

**Issue by tangchunsong** [xinv1996/spiderslab#1]
r:2021-11-16336allcniphone
base64_r:MjAyMS0xMS0xNjMzNmFsbGNuaXBob25l
str_r:MjAyMS0xMS0xNjMzNmFsbGNuaXBob25l@#/rank/indexPlus/brand_id/1@#121924913432@#1
Traceback (most recent call last):
  File "D:/workspace/cctv/qimai/main.py", line 78, in <module>
    an = js.call('get_data', str_r)
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: TypeError: 'undefined' 为 null 或不是对象

**Comment by 01xu10** [comment]
> r:2021-11-16336allcniphone base64_r:MjAyMS0xMS0xNjMzNmFsbGNuaXBob25l str_r:MjAyMS0xMS0xNjMzNmFsbGNuaXBob25l@#/rank/indexPlus/brand_id/1@#121924913432@#1 Traceback (most recent call last): File "D:/workspace/cctv/qimai/main.py", line 78, in an = js.call('get_data', str_r) File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs_abstract_runtime_context.py", line 37, in call return self._call(name, *args) File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs_external_runtime.py", line 92, in _call return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args)) File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs_external_runtime.py", line 78, in _eval return self.exec_(code) File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs_abstract_runtime_context.py", line 18, in exec_ return self._exec_(source) File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs_external_runtime.py", line 88, in _exec_ return self._extract_result(output) File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs_external_runtime.py", line 167, in _extract_result raise ProgramError(value) execjs._exceptions.ProgramError: TypeError: 'undefined' 为 null 或不是对象

请问你解决了吗，我跟你一样的问题
